version: '3.0'
services:
  nats:
    image: nats:2
    ports:
      - '4222:4222'
    restart: unless-stopped
  redis:
    image: redis:6-alpine
    restart: unless-stopped
  mongo:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  traefik:
    image: traefik:1.7.6
    command: >-
      --web --docker --docker.domain=docker.localhost --logLevel=INFO
      --docker.exposedbydefault=false
    ports:
      - '3000:80'
      - '3001:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v2.6.0
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    links:
      - metrics
      - alertmanager:alertmanager
    restart: unless-stopped
  alertmanager:
    image: prom/alertmanager:v0.15.3
    ports:
      - '9093:9093'
    volumes:
      - ./monitoring/alertmanager/:/etc/alertmanager/
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  grafana:
    image: grafana/grafana:5.4.2
    depends_on:
      - prometheus
    ports:
      - '9000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring
    restart: unless-stopped
  v1-accounts:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: accounts.service.js
  v1-acl:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: acl.service.js
  api:
    ports:
      - '4000:4000'
    labels:
      - traefik.enable=true
      - traefik.backend=kantab
      - traefik.port=4000
      - traefik.frontend.entryPoints=http
      - traefik.frontend.rule=PathPrefix:/
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: api.service.js
  v1-boards:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: boards.service.js
  v1-card-activities:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: card.activities.service.js
  v1-card-attachments:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: card.attachments.service.js
  v1-card-checklists:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: card.checklists.service.js
  v1-cards:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: cards.service.js
  v1-config:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: config.service.js
  laboratory:
    expose:
      - 3212
    ports:
      - '3212:3212'
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: laboratory.service.js
  v1-lists:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: lists.service.js
  v1-mail:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: mail.service.js
  metrics:
    image: kantab
    env_file: docker-compose.env
    volumes:
      - app_data:/app/data
      - ./monitoring/prometheus:/app/monitoring/prometheus
    expose:
      - 3030
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped
    environment:
      SERVICES: metrics.service.js
volumes:
  app_data:
    driver: local
  mongo_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
