#########################################################
# cards-checklists service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-checklists-deployment
  namespace: default
  labels:
    name: cards-checklists-deployment
    app: kantab
spec:
  selector:
    matchLabels:
      app: cards-checklists
  replicas: 2
  template:
    metadata:
      labels:
        app: cards-checklists
    spec:
      containers:
        - name: cards-checklists
          image: icebob/kantab:latest
          envFrom:
            - configMapRef:
                name: kantab-configmap
            - secretRef:
                name: kantab-secrets
          env:
            - name: SERVICES
              value: cards.checklists
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 40Mi
---
#########################################################
# Horizontal Pod AutoScaler for cards-checklists service (K8s >= v1.17)
#########################################################
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-cards-checklists
  namespace: default
  labels:
    name: hpa-cards-checklists
    app: kantab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cards-checklists-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---


